#!/bin/sh

/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 1 7 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 8 14 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 15 21 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 22 28 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 29 35 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 36 42 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 43 49 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 50 56 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 57 63 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 64 70 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 71 77 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 78 84 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 85 91 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 92 98 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 99 105 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 106 112 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 113 119 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 120 126 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 127 133 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 134 140 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 141 147 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 148 154 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 155 161 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 162 168 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 169 175 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 176 182 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 183 189 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 190 196 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 197 203 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 204 210 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 211 217 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 218 224 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 225 231 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 232 238 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 239 245 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 246 252 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 253 259 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 260 266 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 267 273 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 274 280 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 281 287 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 288 294 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 295 301 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 302 308 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 309 315 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 316 322 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 323 329 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 330 336 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 337 343 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 344 350 &
/home/jeremy/eclipse-workspace/BasketballBoxScoreDownloader/Debug/BasketballBoxScoreDownloader 351 353 &
wait
