delete from gamebygamedata where team1='AAMU MBB 19-20' and gamedate in ('2019-11-11','2019-11-16');
update gamebygamedata set team1='Alabama A&M' where team1='AAMU MBB 19-20' or team1='Alabama A&M MBB';
update gamebygamedata set team2='Alabama A&M' where team2='AAMU MBB 19-20' or team2='Alabama A&M MBB';
delete from gamebygamedata where team1='Alabama A&M' and gamedate in ('2019-11-15','2019-12-14');
update gamebygamedata set team1='Alabama St.' where team1='Alabama State';
update gamebygamedata set team2='Alabama St.' where team2='Alabama State';
delete from gamebygamedata where team2='Albany' and gamedate='2019-11-13';
delete from gamebygamedata where team1='Alcorn State' and gamedate in ('2019-11-27');
update gamebygamedata set team1='Alcorn' where team1='Alcorn State' or team1='Alcorn St.';
update gamebygamedata set team2='Alcorn' where team2='Alcorn State' or team2='Alcorn St.';
delete from gamebygamedata where team1='Appalachian State' and gamedate in ('2019-12-14');
update gamebygamedata set team1='Appalachian St.' where team1='App State';
update gamebygamedata set team2='Appalachian St.' where team2='App State';
update gamebygamedata set team1='Arizona St.' where team1='ASU' and gamedate='2019-11-26';
update gamebygamedata set team1='Arizona St.' where team1='ASU' or team1='Arizona State';
update gamebygamedata set team2='Arizona St.' where team2='ASU' or team2='Arizona State';
delete from gamebygamedata where team1='Arkansas State' and gamedate in ('2019-11-20');
update gamebygamedata set team1='Arkansas St.' where team1='Arkansas State';
delete from gamebygamedata where team2='Arkansas State' and gamedate in ('2019-11-14','2019-11-15','2019-11-17','2019-11-30','2019-12-03','2020-01-02');
update gamebygamedata set team2='Arkansas St.' where team2='Arkansas State';
delete from gamebygamedata where gamedate='2019-12-14' and team1='Arkansas-Pine Bluff';
update gamebygamedata set team1='Ark.-Pine Bluff' where team1='Arkansas-Pine Bluff';
update gamebygamedata set team2='Ark.-Pine Bluff' where team2='Ark.-Pine Bluff';
update gamebygamedata set team1='Ball St.' where team1='Ball State';
update gamebygamedata set team2='Ball St.' where team2='Ball State';
delete from gamebygamedata where gamedate='2019-11-22' and team1='Baylor' and team2='Coastal Carolina';
update gamebygamedata set team1='Boise St.' where team1='Boise State';
update gamebygamedata set team2='Boise St.' where team2='Boise State';
update gamebygamedata set team1='Boston U.' where team1='Boston University';
update gamebygamedata set team1='Boston U.' where team1='Boston U';
delete from gamebygamedata where team2='Boston University' and gamedate in ('2019-11-27');
update gamebygamedata set team2='Boston U.' where team2='Boston University';
update gamebygamedata set team2='Boston U.' where team2='Boston U';
update gamebygamedata set team1='Cal St. Fullerton' where team1='Cal State Fullerton';
update gamebygamedata set team2='Cal St. Fullerton' where team2='Cal St. Fullerton';
update gamebygamedata set team1='Long Beach St.' where team1='Long Beach State' or team1='LBSU';
update gamebygamedata set team2='Long Beach St.' where team2='Long Beach State' or team2='LBSU';
delete from gamebygamedata where gamedate='2019-12-01' and team1='Campbell' and team2='FGCU';
delete from gamebygamedata where team1='Central Ark.' and gamedate in ('2019-11-10','2019-11-12','2019-11-22','2019-12-14','2019-12-28');
update gamebygamedata set team1='Central Arkansas' where team1='Central Ark.';
delete from gamebygamedata where team2='Central Ark.' and gamedate in ('2019-11-17','2019-11-23');
update gamebygamedata set team2='Central Arkansas' where team2='Central Ark.';
update gamebygamedata set team1='Central Conn. St.' where team1='CCSU' or team1='Central Conn. State';
update gamebygamedata set team2='Central Conn. St.' where team2='CCSU' or team2='Central Conn. State';
delete from gamebygamedata where gamedate='2019-11-12' and team1='Miami (FL)' and team2='UCF';
update gamebygamedata set team1='Central Michigan' where team1='Central Mich.';
delete from gamebygamedata where team2='Central Mich.' and gamedate in ('2019-12-06');
update gamebygamedata set team2='Central Michigan' where team2='Central Mich.';
delete from gamebygamedata where team1='Charleston So.' and gamedate in ('2019-11-16','2019-11-18','2019-12-16');
update gamebygamedata set team1='Charleston Southern' where team1='Charleston So.';
delete from gamebygamedata where team2='Charleston So.' and gamedate in ('2019-11-12','2019-11-23','2019-12-07','2020-01-02');
update gamebygamedata set team2='Charleston Southern' where team2='Charleston So.';
update gamebygamedata set team1='Chicago St.' where team1='Chicago State';
update gamebygamedata set team2='Chicago St.' where team2='Chicago State';
delete from gamebygamedata where team2='Cincinnati' and gamedate in ('2019-12-01','2019-12-04','2019-12-15','2019-12-19','2020-01-02');
update gamebygamedata set team1='Cleveland St.' where team1='Cleveland State';
update gamebygamedata set team2='Cleveland St.' where team2='Cleveland State';
delete from gamebygamedata where gamedate='2019-11-19' and team1='Middle Tenn.' and team2='Coastal Carolina';
update gamebygamedata set team1='Col. of Charleston' where team1='CHARLESTON';
delete from gamebygamedata where team1='Colorado State' and gamedate in ('2019-12-21','2020-01-01');
update gamebygamedata set team1='Colorado St.' where team1='Colorado State';
delete from gamebygamedata where team2='Colorado State' and gamedate in ('2019-12-13','2020-01-04');
update gamebygamedata set team2='Colorado St.' where team2='Colorado State';
delete from gamebygamedata where gamedate='2019-12-04' and team1='Iona College' and team2='Connecticut';
delete from gamebygamedata where team1='Coppin State' and gamedate in ('2019-11-29','2019-12-21');
update gamebygamedata set team1='Coppin St.' where team1='Coppin State';
update gamebygamedata set team2='Coppin St.' where team2='Coppin State';
delete from gamebygamedata where gamedate='2019-12-21' and team1='Coppin St.' and team2='Miami';
update gamebygamedata set team1='Delaware St.' where team1='Delaware State' or team1='Delaware State-men';
update gamebygamedata set team2='Delaware St.' where team2='Delaware State' or team2='Delaware State-men';
delete from gamebygamedata where team1='East Carolina Pirates' or team2='East Carolina Pirates';
delete from gamebygamedata where team1='Eastern Illnois' and gamedate in ('2019-11-05');
update gamebygamedata set team1='Eastern Illinois' where team1='Eastern Illnois' or team1='Eastern Ill.';
update gamebygamedata set team2='Eastern Illinois' where team2='Eastern Illnois' or team2='Eastern Ill.';
update gamebygamedata set team1='Eastern Kentucky' where team1='Eastern Ky.';
update gamebygamedata set team2='Eastern Kentucky' where team2='Eastern Ky.';
delete from gamebygamedata where gamedate='2019-12-21' and team1='Eastern Mich.';
delete from gamebygamedata where gamedate='2019-11-24' and team1='NCAT';
delete from gamebygamedata where team1='Eastern Mich.' and gamedate in ('2019-11-30','2019-12-28');
update gamebygamedata set team1='Eastern Michigan' where team1='Eastern Mich.';
update gamebygamedata set team2='Eastern Michigan' where team2='Eastern Mich.';
delete from gamebygamedata where team1='Eastern Wash.' and gamedate in ('2019-11-20');
update gamebygamedata set team1='Eastern Washington' where team1='Eastern Wash.';
update gamebygamedata set team2='Eastern Washington' where team2='Eastern Wash.';
delete from gamebygamedata where team1='Evansville Purple Aces' and gamedate in ('2019-11-23','2019-11-24');
update gamebygamedata set team1='Evansville' where team1='Evansville Purple Aces';
update gamebygamedata set team2='Evansville' where team2='Evansville Purple Aces';
delete from gamebygamedata where team1='Fla. Atlantic' and gamedate in ('2019-11-21','2019-12-29');
update gamebygamedata set team1='Florida Atlantic' where team1='FAU' or team1='Fla. Atlantic';
update gamebygamedata set team2='Florida Atlantic' where team2='FAU' or team2='Fla. Atlantic';
delete from gamebygamedata where gamedate='2019-11-21' and team1='Florida Atlantic' and team2='FGCU';
delete from gamebygamedata where gamedate='2019-12-08' and team1='Robert Morris' and team2='FGCU';
update gamebygamedata set team1='Florida St.' where team1='Florida State';
update gamebygamedata set team2='Florida St.' where team2='Florida State';
delete from gamebygamedata where team1='Fresno State' and gamedate in ('2019-11-30');
update gamebygamedata set team1='Fresno St.' where team1='Fresno State';
update gamebygamedata set team2='Fresno St.' where team2='Fresno State';
delete from gamebygamedata where gamedate='2019-11-29' and team1='George Washington' and team2='Milwaukee Panthers';
delete from gamebygamedata where team1='Ga. Southern' and gamedate in ('2020-01-06');
update gamebygamedata set team1='Georgia Southern' where team1='Ga. Southern';
delete from gamebygamedata where team2='Ga. Southern' and gamedate in ('2019-11-15');
update gamebygamedata set team2='Georgia Southern' where team2='Ga. Southern';
update gamebygamedata set team1='Georgia St.' where team1='Georgia State';
update gamebygamedata set team2='Georgia St.' where team2='Georgia State';
delete from gamebygamedata where team1='#8 Gonzaga' and gamedate in ('2019-11-29');
delete from gamebygamedata where gamedate='2019-11-23' and team1='Grambling State' and team2='Oregon State';
update gamebygamedata set team1='Grambling' where team1='Grambling St MBB' or team1='Grambling State' or team1='Grambling St.';
update gamebygamedata set team2='Grambling' where team2='Grambling St MBB' or team2='Grambling State' or team2='Grambling St.';
update gamebygamedata set team1='Harvard' where team1='Harvard University';
update gamebygamedata set team2='Harvard' where team2='Harvard University';
update gamebygamedata set team1='High Point' where team1='HPUMBB';
update gamebygamedata set team2='High Point' where team2='HPUMBB';
delete from gamebygamedata where team1='Howard University' and gamedate in ('2019-11-09','2019-11-15','2019-11-17','2019-11-23','2019-11-26','2019-12-05');
update gamebygamedata set team1='Howard' where team1='Howard University';
update gamebygamedata set team2='Howard' where team2='Howard University';
delete from gamebygamedata where team1='Idaho State' and gamedate in ('2019-12-06');
update gamebygamedata set team1='Idaho St.' where team1='Idaho State';
update gamebygamedata set team2='Idaho St.' where team2='Idaho State';
delete from gamebygamedata where team1='Illinois State' and gamedate in ('2019-12-03');
update gamebygamedata set team1='Illinois St.' where team1='Illinois State';
update gamebygamedata set team2='Illinois St.' where team2='Illinois State';
delete from gamebygamedata where team1='UIW' and gamedate in ('2019-11-06','2019-11-08');
update gamebygamedata set team1='Incarnate Word' where team1='UIW';
update gamebygamedata set team2='Incarnate Word' where team2='UIW';
update gamebygamedata set team1='Indiana St.' where team1='Indiana State';
update gamebygamedata set team2='Indiana St.' where team2='Indiana State';
delete from gamebygamedata where team1='Iona College' and gamedate in ('2019-11-09','2019-12-17','2019-12-29','2020-01-05');
update gamebygamedata set team1='Iona' where team1='Iona College';
delete from gamebygamedata where team2='Iona College' and gamedate in ('2019-11-22','2020-01-03');
update gamebygamedata set team2='Iona' where team2='Iona College';
delete from gamebygamedata where gamedate='2019-11-09' and team1='Iowa State' and team2='Oregon State';
delete from gamebygamedata where gamedate='2019-11-13' and team1='Northern Illinois' and team2='Iowa State';
delete from gamebygamedata where gamedate='2019-12-05' and team1='Kansas City' and team2='Iowa State';
delete from gamebygamedata where gamedate='2019-12-09' and team1='Seton Hall' and team2='Iowa State';
update gamebygamedata set team1='Iowa St.' where team1='Iowa State';
update gamebygamedata set team2='Iowa St.' where team2='Iowa State';
update gamebygamedata set team1='Jackson St.' where team1='Jackson State';
update gamebygamedata set team2='Jackson St.' where team2='Jackson State';
update gamebygamedata set team1='Jacksonville St.' where team1='Jacksonville State';
update gamebygamedata set team2='Jacksonville St.' where team2='Jacksonville State';
update gamebygamedata set team1='James Madison' where team1='JMU';
update gamebygamedata set team2='James Madison' where team2='JMU';
update gamebygamedata set team1='Kansas St.' where team1='Kansas State';
update gamebygamedata set team2='Kansas St.' where team2='Kansas State';
delete from gamebygamedata where gamedate='2019-11-18' and team1='Reinhardt' and team2='Kennesaw St.';
delete from gamebygamedata where team1='Kennesaw State' and gamedate in ('2019-11-07','2019-11-11','2019-11-22','2019-12-16','2019-12-29');
update gamebygamedata set team1='Kennesaw St.' where team1='Kennesaw State';
delete from gamebygamedata where team2='Kennesaw State' and gamedate in ('2019-11-23','2019-12-07','2019-12-13');
update gamebygamedata set team2='Kennesaw St.' where team2='Kennesaw State';
update gamebygamedata set team1='Kent St.' where team1='Kent State';
update gamebygamedata set team2='Kent St.' where team2='Kent State';
delete from gamebygamedata where team2='#8/10 Kentucky' and gamedate in ('2019-12-07');
delete from gamebygamedata where team2='#3 Maryland' and gamedate in ('2019-12-07');
update gamebygamedata set team1='Louisville' where team1='#5 Louisville';
update gamebygamedata set team1='North Carolina' where team1='#6 North Carolina';
delete from gamebygamedata where team2='# Michigan' and gamedate in ('2019-11-28');
update gamebygamedata set team1='Tennessee' where team1='#17 Tennessee';
update gamebygamedata set team2='Virginia Commonwealth' where team2='#20 Virginia Commonwealth';
update gamebygamedata set team1='Lamar' where team1='Lamar University';
update gamebygamedata set team2='Lamar' where team2='Lamar University';
update gamebygamedata set team1='Liberty' where team1='Liberty Flames';
update gamebygamedata set team2='Liberty' where team2='Liberty Flames';
delete from gamebygamedata where team1='LIU' and gamedate in ('2019-11-13','2019-11-22','2019-11-24','2019-11-28','2019-12-07','2019-12-14');
update gamebygamedata set team1='Long Island University' where team1='LIU';
delete from gamebygamedata where team2='LIU' and gamedate in ('2019-11-08','2019-12-20');
update gamebygamedata set team2='Long Island University' where team2='LIU';
update gamebygamedata set team1='UMES' where team1='Md. Eastern Shore';
update gamebygamedata set team2='UMES' where team2='Md. Eastern Shore';
update gamebygamedata set team1='UMES' where team1='Maryland Eastern Shore';
update gamebygamedata set team2='UMES' where team2='Maryland Eastern Shore';
update gamebygamedata set team1='Miami (FL)' where gamedate='2019-11-24' and team2='UConn';
update gamebygamedata set team1='Michigan St.' where team1='Michigan State';
update gamebygamedata set team2='Michigan St.' where team2='Michigan State';
delete from gamebygamedata where team1='Middle Tenn.' and gamedate in ('2019-12-14');
update gamebygamedata set team1='Middle Tennessee' where team1='Middle Tenn.';
update gamebygamedata set team2='Middle Tennessee' where team2='Middle Tenn.';
update gamebygamedata set team1='Milwaukee' where team1='Milwaukee Panthers';
update gamebygamedata set team2='Milwaukee' where team2='Milwaukee Panthers';
update gamebygamedata set team1='Ole Miss' where team1='Mississippi';
update gamebygamedata set team2='Ole Miss' where team2='Mississippi';
update gamebygamedata set team1='Mississippi St.' where team1='Mississippi State';
update gamebygamedata set team2='Mississippi St.' where team2='Mississippi State';
update gamebygamedata set team1='Miss. Valley St.' where team1='Mississippi Val.' or team1='Mississippi Valley' or team1='Miss. Valley State';
update gamebygamedata set team2='Miss. Valley St.' where team2='Mississippi Val.' or team2='Mississippi Valley' or team2='Miss. Valley State';
update gamebygamedata set team1='Missouri St.' where team1='Missouri State';
update gamebygamedata set team2='Missouri St.' where team2='Missouri State';
update gamebygamedata set team1='Missouri' where team1='Mizzou';
delete from gamebygamedata where team2='Mizzou' and gamedate in ('2019-11-20');
update gamebygamedata set team2='Missouri' where team2='Mizzou';
update gamebygamedata set team1='Kansas City' where team1='Kansas City Roos';
update gamebygamedata set team2='Kansas City' where team2='Kansas City Roos';
delete from gamebygamedata where gamedate='2019-11-10' and team1='Monmouth' and team2='Princeton';
update gamebygamedata set team1='Montana St.' where team1='Montana State';
update gamebygamedata set team2='Montana St.' where team2='Montana State';
update gamebygamedata set team1='Morehead St.' where team1='Morehead State';
update gamebygamedata set team2='Morehead St.' where team2='Morehead State';
delete from gamebygamedata where lower(team1)='morgan state' and gamedate in ('2019-11-09','2019-11-16','2019-12-14','2019-12-28');
update gamebygamedata set team1='Morgan St.' where lower(team1)='morgan state';
update gamebygamedata set team2='Morgan St.' where lower(team2)='morgan state';
update gamebygamedata set team1='Mount St. Mary''s' where lower(team1)='mt. st. mary''s';
update gamebygamedata set team2='Mount St. Mary''s' where lower(team2)='mt. st. mary''s';
update gamebygamedata set team1='Murray St.' where lower(team1)='murray state';
delete from gamebygamedata where lower(team2)='murray state' and gamedate in ('2020-01-02');
update gamebygamedata set team2='Murray St.' where lower(team2)='murray state';
update gamebygamedata set team1='New Hampshire' where team1='NH';
update gamebygamedata set team2='New Hampshire' where team2='NH';
update gamebygamedata set team1='New Mexico St.' where team1='New Mexico State';
update gamebygamedata set team2='New Mexico St.' where team2='New Mexico State';
update gamebygamedata set team1='Nicholls St.' where team1='Nicholls State';
update gamebygamedata set team2='Nicholls St.' where team2='Nicholls State';
delete from gamebygamedata where team1='Norfolk State' and gamedate in ('2019-11-22','2019-11-27','2019-12-04','2019-12-20','2019-12-21','2019-12-29','2020-01-06');
update gamebygamedata set team1='Norfolk St.' where team1='Norfolk State';
update gamebygamedata set team2='Norfolk St.' where team2='Norfolk State';
delete from gamebygamedata where gamedate='2019-11-19' and team1='North Ala.' and team2='South Dakota State';
delete from gamebygamedata where (team1='North Ala.' or team1='UNA') and gamedate in ('2019-11-12','2019-11-22','2019-12-04','2019-12-20');
update gamebygamedata set team1='North Alabama' where team1='North Ala.' or team1='UNA';
delete from gamebygamedata where (team2='North Ala.' or team2='UNA') and gamedate in ('2019-11-16');
update gamebygamedata set team2='North Alabama' where team2='North Ala.' or team2='UNA';
delete from gamebygamedata where (team1='NCAT' or team1='N.C. A&T') and gamedate in ('2019-11-12','2019-11-15','2019-11-19','2019-12-07','2019-12-16','2019-12-29');
update gamebygamedata set team1='North Carolina A&T' where team1='NCAT' or team1='N.C. A&T';
delete from gamebygamedata where (team2='NCAT' or team2='N.C. A&T') and gamedate in ('2019-11-22','2019-12-17');
update gamebygamedata set team2='North Carolina A&T' where team2='NCAT' or team2='N.C. A&T';
delete from gamebygamedata where team1='UNC Greensboro' and gamedate in ('2019-11-30');
update gamebygamedata set team1='UNCG' where team1='UNC Greensboro';
update gamebygamedata set team2='UNCG' where team2='UNC Greensboro';
update gamebygamedata set team1='UNCW' where team1='UNC Wilmington';
update gamebygamedata set team2='UNCW' where team2='UNC Wilmington';
update gamebygamedata set team1='North Florida' where team1='UNF';
update gamebygamedata set team2='North Florida' where team2='UNF';
update gamebygamedata set team1='Northern Colorado' where team1='Northern Colo.';
delete from gamebygamedata where team2='Northern Colo.' and gamedate in ('2020-01-04');
update gamebygamedata set team2='Northern Colorado' where team2='Northern Colo.';
delete from gamebygamedata where gamedate='2019-11-05' and team1='Roosevelt' and team2='Northern Ill.';
update gamebygamedata set team1='Northern Illinois' where team1='Northern Ill.';
update gamebygamedata set team2='Northern Illinois' where team2='Northern Ill.';
update gamebygamedata set team1='Northern Iowa' where team1='UNI';
delete from gamebygamedata where team2='UNI' and gamedate in ('2020-01-04','2019-11-19');
update gamebygamedata set team2='Northern Iowa' where team2='UNI';
update gamebygamedata set team1='Northern Kentucky' where team1='Northern Ky.';
update gamebygamedata set team2='Northern Kentucky' where team2='Northern Ky.';
update gamebygamedata set team1='Ohio St.' where team1='Ohio State';
update gamebygamedata set team2='Ohio St.' where team2='Ohio State';
delete from gamebygamedata where team1='Oklahoma State' and gamedate in ('2019-11-13','2019-12-15');
update gamebygamedata set team1='Oklahoma St.' where team1='Oklahoma State';
update gamebygamedata set team2='Oklahoma St.' where team2='Oklahoma State';
update gamebygamedata set team1='Old Dominion' where team1='ODU';
update gamebygamedata set team2='Old Dominion' where team2='ODU';
delete from gamebygamedata where team1='Oregon State' and gamedate in ('2019-12-21','2020-01-02','2020-01-05');
update gamebygamedata set team1='Oregon St.' where team1='Oregon State';
delete from gamebygamedata where team2='Oregon State' and gamedate in ('2019-11-05','2019-11-12','2019-11-27','2019-12-01','2019-12-29');
update gamebygamedata set team2='Oregon St.' where team2='Oregon State';
delete from gamebygamedata where team2='Pitt' and gamedate in ('2019-12-30');
delete from gamebygamedata where team1='Portland State' and gamedate in ('2019-11-15','2019-12-17');
update gamebygamedata set team1='Portland St.' where team1='Portland State';
update gamebygamedata set team2='Portland St.' where team2='Portland State';
update gamebygamedata set team1='Princeton' where team1='PRIN';
update gamebygamedata set team2='Princeton' where team2='PRIN';
update gamebygamedata set team1='Rice' where team1='Rice Owls';
delete from gamebygamedata where team2='Rice Owls' and gamedate in ('2019-11-22');
update gamebygamedata set team2='Rice' where team2='Rice Owls';
delete from gamebygamedata where gamedate='2019-12-08' and team1='Robert Morris' and team2='FGCU';
update gamebygamedata set team1='Saint Francis (PA)' where team1='SAINT FRANCIS';
update gamebygamedata set team2='Saint Francis (PA)' where team2='SAINT FRANCIS';
update gamebygamedata set team1='Saint Joseph''s' where team1='SJU';
update gamebygamedata set team2='Saint Joseph''s' where team2='SJU';
update gamebygamedata set team1='Sam Houston St.' where team1='Sam Houston State';
update gamebygamedata set team2='Sam Houston St.' where team2='Sam Houston State';
update gamebygamedata set team1='San Diego St.' where team1='San Diego State';
update gamebygamedata set team2='San Diego St.' where team2='San Diego State';
delete from gamebygamedata where team1='San Jose State' and gamedate in ('2019-11-06','2019-11-14','2019-12-01');
update gamebygamedata set team1='San Jose St.' where team1='San Jose State';
delete from gamebygamedata where team2='San Jose State' and gamedate in ('2019-12-14','2019-12-22','2019-12-28');
update gamebygamedata set team2='San Jose St.' where team2='San Jose State';
delete from gamebygamedata where team1='Seattle' and gamedate in ('2019-11-19');
update gamebygamedata set team1='Seattle U' where team1='Seattle';
update gamebygamedata set team2='Seattle U' where team2='Seattle';
update gamebygamedata set team1='South Carolina St.' where team1='South Carolina State' or team1='South Carolina State Bulldogs' or team1='S.C. State';
update gamebygamedata set team2='South Carolina St.' where team2='South Carolina State' or team2='South Carolina State Bulldogs' or team2='S.C. State';
delete from gamebygamedata where team1='South Dakota State' and gamedate in ('2019-11-09','2019-11-12','2019-11-15','2019-11-21');
update gamebygamedata set team1='South Dakota St.' where team1='South Dakota State';
update gamebygamedata set team2='South Dakota St.' where team2='South Dakota State';
update gamebygamedata set team1='South Florida' where team1='South Fla.';
delete from gamebygamedata where team2='South Fla.' and gamedate in ('2019-12-02');
update gamebygamedata set team2='South Florida' where team2='South Fla.';
delete from gamebygamedata where team1='Southeast Missouri' and gamedate in ('2019-12-05');
update gamebygamedata set team1='Southeast Missouri St.' where team1='Southeast Mo. St.' or team1='Southeast Missouri';
update gamebygamedata set team2='Southeast Missouri St.' where team2='Southeast Mo. St.' or team2='Southeast Missouri';
delete from gamebygamedata where lower(team1)='southeastern la' and gamedate in ('2019-12-21','2019-12-29','2020-01-04');
update gamebygamedata set team1='Southeastern Louisiana' where lower(team1)='southeastern louisia' or lower(team1)='southeastern la' or lower(team1)='southeastern la.';
update gamebygamedata set team2='Southeastern Louisiana' where lower(team2)='southeastern louisia' or lower(team2)='southeastern la' or lower(team2)='southeastern la.';
update gamebygamedata set team1='USC' where lower(team1)='southern cal' or lower(team1)='southern california';
delete from gamebygamedata where team2='Southern California' and gamedate in ('2019-11-19');
update gamebygamedata set team2='USC' where lower(team2)='southern cal' or lower(team2)='southern california';
update gamebygamedata set team1='Southern Illinois' where lower(team1)='southern ill.' or lower(team1)='siu';
update gamebygamedata set team2='Southern Illinois' where lower(team2)='southern ill.' or lower(team2)='siu';
update gamebygamedata set team1='Southern' where lower(team1)='southern u.' ;
update gamebygamedata set team2='Southern' where lower(team2)='southern u.';
delete from gamebygamedata where team1='Southern Miss.' and gamedate in ('2020-01-04','2019-11-29');
update gamebygamedata set team1='Southern Miss' where lower(team1)='southern miss.' ;
delete from gamebygamedata where team2='Southern Miss.' and gamedate in ('2019-11-28');
update gamebygamedata set team2='Southern Miss' where lower(team2)='southern miss.';
update gamebygamedata set team1='St. Bonaventure' where lower(team1)='sbum' ;
update gamebygamedata set team2='St. Bonaventure' where lower(team2)='sbum';
delete from gamebygamedata where lower(team1)='st. john''s (ny)' and gamedate in ('2019-12-21','2020-01-05');
update gamebygamedata set team1='St. John''s' where lower(team1)='st. john''s (ny)';
delete from gamebygamedata where lower(team2)='st. john''s (ny)' and gamedate in ('2019-11-06','2019-11-12','2019-11-16','2019-11-20','2019-11-23','2019-11-24','2019-11-30','2019-12-03','2019-12-07','2019-12-18','2019-12-31');
update gamebygamedata set team2='St. John''s' where lower(team2)='st. john''s (ny)';
update gamebygamedata set team1='Tennessee St.' where lower(team1)='tennessee state';
update gamebygamedata set team2='Tennessee St.' where lower(team2)='tennessee state';
update gamebygamedata set team1='Tennessee' where lower(team1)='#17 tennessee';
update gamebygamedata set team2='Tennessee' where lower(team2)='#17 tennessee';
delete from gamebygamedata where lower(team1)='texas state' and gamedate in ('2019-12-04');
update gamebygamedata set team1='Texas St.' where lower(team1)='texas state';
update gamebygamedata set team2='Texas St.' where lower(team2)='texas state';
update gamebygamedata set team1='UT Arlington' where lower(team1)='texas-arlington';
update gamebygamedata set team2='UT Arlington' where lower(team2)='texas-arlington';
update gamebygamedata set team1='UTRGV' where lower(team1)='ut rio grande valley';
update gamebygamedata set team2='UTRGV' where lower(team2)='ut rio grande valley';
delete from gamebygamedata where lower(team1)='troy university' and gamedate in ('2019-11-16','2019-11-20','2019-11-23');
update gamebygamedata set team1='Troy' where lower(team1)='troy university';
delete from gamebygamedata where lower(team2)='troy university' and gamedate in ('2019-11-07');
update gamebygamedata set team2='Troy' where lower(team2)='troy university';
delete from gamebygamedata where lower(team1)='utah state' and gamedate in ('2019-11-22','2019-11-29','2019-12-21','2020-01-01');
update gamebygamedata set team1='Utah St.' where lower(team1)='utah state';
delete from gamebygamedata where lower(team2)='utah state' and gamedate in ('2019-11-24');
update gamebygamedata set team2='Utah St.' where lower(team2)='utah state';
update gamebygamedata set team1='VCU' where lower(team1)='#20 virginia commonwealth';
update gamebygamedata set team2='VCU' where lower(team2)='#20 virginia commonwealth';
update gamebygamedata set team1='VCU' where lower(team1)='virginia commonwealth';
update gamebygamedata set team2='VCU' where lower(team2)='virginia commonwealth';
update gamebygamedata set team1='VMI' where lower(team1)='keydets';
update gamebygamedata set team2='VMI' where lower(team2)='keydets';
update gamebygamedata set team1='Washington St.' where lower(team1)='washington state';
update gamebygamedata set team2='Washington St.' where lower(team2)='washington state';
update gamebygamedata set team1='Weber St.' where lower(team1)='weber state';
update gamebygamedata set team2='Weber St.' where lower(team2)='weber state';
delete from gamebygamedata where lower(team1)='western caro.' and gamedate in ('2019-11-05','2019-11-21','2019-11-24','2019-12-18');
update gamebygamedata set team1='Western Carolina' where lower(team1)='western caro.';
delete from gamebygamedata where lower(team2)='western caro.' and gamedate in ('2019-12-03','2019-12-07');
update gamebygamedata set team2='Western Carolina' where lower(team2)='western caro.';
update gamebygamedata set team1='Western Illinois' where lower(team1)='western ill.';
delete from gamebygamedata where lower(team2)='western ill.' and gamedate in ('2019-11-13','2019-12-29');
update gamebygamedata set team2='Western Illinois' where lower(team2)='western ill.';
update gamebygamedata set team1='Western Kentucky' where lower(team1)='western ky.' or lower(team1)='wku';
update gamebygamedata set team2='Western Kentucky' where lower(team2)='western ky.' or lower(team2)='wku';
delete from gamebygamedata where lower(team1)='western mich.' and gamedate in ('2019-12-14');
update gamebygamedata set team1='Western Michigan' where lower(team1)='western mich.';
update gamebygamedata set team2='Western Michigan' where lower(team2)='western mich.';
update gamebygamedata set team1='Wichita St.' where lower(team1)='wichita state';
delete from gamebygamedata where lower(team2)='wichita state' and gamedate in ('2019-11-16');
update gamebygamedata set team2='Wichita St.' where lower(team2)='wichita state';
update gamebygamedata set team1='Wright St.' where lower(team1)='wright state';
update gamebygamedata set team2='Wright St.' where lower(team2)='wright state';
delete from gamebygamedata where gamedate='2019-11-30' and team1='Xavier' and team2='New Orleans';
update gamebygamedata set team1='Youngstown St.' where lower(team1)='youngstown state';
update gamebygamedata set team2='Youngstown St.' where lower(team2)='youngstown state';